### ISSUE TITLE
update yuh

### ISSUE THREAD

**Issue by Jakee8718** [novak5712/proxy-scraper-checker#1]
heres my proxies daddy 
add but add credit
https://github.com/Jakee8718/Free-Proxies

**Comment by novak5712** [comment]
i would rather kill myself tbf, you barely update your list

**Comment by Jakee8718** [comment]
pov the commits

**Comment by novak5712** [comment]
you're a skid

**Comment by Jakee8718** [comment]
Omg thats so real. how exactly? did i steal ur proxiess!?!?!?! omgggg.... i didnt, and they aint urs. either way yo shi aahhhh
